steps:
  - label: ":docker: :package:"
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.3.0:
        build: test
        image-repository: 243200153905.dkr.ecr.us-east-1.amazonaws.com/availability-engine-ci
        cache-from:
          - test:243200153905.dkr.ecr.us-east-1.amazonaws.com/availability-engine-ci:latest
        push:
          - test:243200153905.dkr.ecr.us-east-1.amazonaws.com/availability-engine-ci:latest
        push-retries: 4
        pull-retries: 2
  - wait
